INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (1, 7, 'Aegean Paradise');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (2, 7, 'AIDAaura');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (3, 2, 'AIDAbella');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (4, 2, 'AIDAblu');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (5, 3, 'AIDAcara');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (6, 5, 'AIDAdiva');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (7, 1, 'AIDAluna');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (8, 6, 'AIDAmar');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (9, 8, 'AIDAprima');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (10, 8, 'AIDAsol');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (11, 2, 'AIDAstella');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (12, 2, 'AIDAvita');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (13, 3, 'Allure of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (14, 8, 'American Eagle');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (15, 4, 'Arosa Star');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (16, 6, 'Arosa Sun');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (17, 6, 'Athena');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (18, 1, 'Atlantic Star');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (19, 8, 'Aurora Star');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (20, 5, 'Azamara Journey');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (21, 4, 'Azamara Quest');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (22, 7, 'Balmoral');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (23, 7, 'Belofin I');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (24, 3, 'The Big Red Boat');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (25, 5, 'Black Watch');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (26, 5, 'Britannia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (27, 1, 'Caribbean Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (28, 3, 'Carnival Breeze');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (29, 7, 'Carnival Conquest');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (30, 5, 'Carnival Destiny');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (31, 1, 'Carnival Dream');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (32, 8, 'Carnival Ecstasy');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (33, 7, 'Carnival Elation');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (34, 5, 'Carnival Fantasy');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (35, 2, 'Carnival Fascination');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (36, 8, 'Carnival Freedom');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (37, 3, 'Carnival Glory');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (38, 7, 'Carnival Imagination');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (39, 3, 'Carnival Inspiration');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (40, 4, 'Carnival Legend');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (41, 8, 'Carnival Liberty');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (42, 8, 'Carnival Magic');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (43, 6, 'Carnival Miracle');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (44, 7, 'Carnival Paradise');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (45, 5, 'Carnival Pride');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (46, 1, 'Carnival Sensation');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (47, 2, 'Carnival Spirit');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (48, 3, 'Carnival Splendor');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (49, 8, 'Carnival Sunshine');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (50, 7, 'Carnival Triumph');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (51, 6, 'Carnival Valor');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (52, 1, 'Carnival Victory');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (53, 8, 'Carnival Vista');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (54, 8, 'Carnivale');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (55, 6, 'Celebration');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (56, 8, 'Celebrity Century');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (57, 1, 'Celebrity Constellation');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (58, 8, 'Celebrity Eclipse');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (59, 5, 'Celebrity Equinox');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (60, 7, 'Celebrity Infinity');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (61, 5, 'Celebrity Millennium');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (62, 6, 'Celebrity Reflection');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (63, 7, 'Celebrity Silhouette');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (64, 4, 'Celebrity Solstice');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (65, 7, 'Celebrity Summit');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (66, 2, 'Celebrity Xpedition');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (67, 3, 'Celestyal Crystal');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (68, 7, 'Clio');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (69, 6, 'Clipper Odyssey');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (70, 5, 'Club Med 2');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (71, 3, 'Constitution');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (72, 8, 'Coral Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (73, 7, 'Costa Allegra');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (74, 5, 'Costa Atlantica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (75, 6, 'Costa Pacifica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (76, 4, 'Costa Classica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (77, 1, 'Costa Concordia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (78, 8, 'Costa Deliziosa');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (79, 6, 'Costa Diadema');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (80, 5, 'Costa Fortuna');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (81, 4, 'Costa Fascinosa');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (82, 6, 'Costa Favolosa');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (83, 4, 'Costa Fortuna');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (84, 1, 'Costa Luminosa');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (85, 7, 'Costa Magica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (86, 8, 'Costa Mediterranea');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (87, 8, 'Costa neoRiviera');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (88, 8, 'Costa neoRomantica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (89, 7, 'Costa Serena');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (90, 2, 'Costa Victoria');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (91, 7, 'Costa Voyager');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (92, 4, 'Crown Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (93, 2, 'Crystal Serenity');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (94, 5, 'Crystal Symphony');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (95, 7, 'Cunard Ambassador');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (96, 2, 'Dawn Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (97, 2, 'Diamond Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (98, 3, 'Discovery');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (99, 8, 'Disney Dream');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (100, 3, 'Disney Fantasy');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (101, 6, 'Disney Magic');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (102, 4, 'Disney Wonder');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (103, 5, 'easyCruiseOne');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (104, 3, 'Emerald Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (105, 4, 'Empress');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (106, 6, 'Enchanted Capri');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (107, 3, 'Enchantment of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (108, 3, 'Explorer of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (109, 3, 'Fairland');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (110, 2, 'Fairsky');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (111, 8, 'RMS Franconia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (112, 1, 'Freedom of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (113, 2, 'Freewinds');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (114, 1, 'Gemini');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (115, 3, 'Golden Iris');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (116, 7, ' Golden Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (117, 2, 'Grand Celebration');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (118, 6, 'Grand Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (119, 5, 'Grandeur of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (120, 7, 'Harmony of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (121, 3, 'Harmony Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (122, 4, 'Henna');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (123, 8, 'Independence of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (124, 5, 'Independence');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (125, 7, 'Island Escape');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (126, 7, 'Island Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (127, 6, 'Island Sky');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (128, 2, 'Jewel of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (129, 6, 'L''Amant');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (130, 4, 'L''Austral');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (131, 3, 'Le Bor�al');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (132, 7, 'Le Diamant');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (133, 8, 'Le Levant');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (134, 3, 'Le Ponant');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (135, 7, 'Legacy');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (136, 1, 'Legend of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (137, 2, 'Liberty of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (138, 1, 'Louis Olympia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (139, 5, 'SS Lurline (1931)');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (140, 1, 'Magellan');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (141, 6, 'Majesty of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (142, 5, 'Macau Success');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (143, 6, 'Mandalay');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (144, 6, 'Mariner of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (145, 3, 'RMS Mauretania');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (146, 6, 'RMS Mauretania II');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (147, 3, 'Mein Schiff 1');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (148, 2, 'Mein Schiff 2');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (149, 2, 'Mein Schiff 3');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (150, 1, 'Mein Schiff 4');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (151, 1, 'Mein Schiff 5');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (152, 4, 'Mikhail Lermontov');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (153, 6, 'Midnatsol');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (154, 2, 'Minerva');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (155, 1, 'Mona Lisa');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (156, 3, 'MSC Armonia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (157, 4, 'MSC Divina');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (158, 8, 'MSC Fantasia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (159, 5, 'MSC Lirica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (160, 5, 'MSC Magnifica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (161, 1, 'MSC Melody');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (162, 2, 'MSC Musica');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (163, 5, 'MSC Opera');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (164, 7, 'MSC Orchestra');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (165, 7, 'MSC Poesia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (166, 1, 'MSC Sinfonia');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (167, 2, 'MSC Splendida');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (168, 7, 'National Geographic Endeavour');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (169, 3, 'National Geographic Explorer');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (170, 3, 'Navigator of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (171, 5, 'SS Norway');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (172, 1, 'Norwegian Bliss');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (173, 2, 'Norwegian Dawn');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (174, 5, 'Norwegian Epic');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (175, 2, 'Norwegian Escape');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (176, 6, 'Norwegian Getaway');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (177, 7, 'Norwegian Gem');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (178, 3, 'Norwegian Jade');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (179, 3, 'Norwegian Jewel');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (180, 1, 'Norwegian Pearl');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (181, 5, 'Norwegian Spirit');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (182, 5, 'Norwegian Sky');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (183, 8, 'Norwegian Star');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (184, 6, 'Norwegian Sun');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (185, 3, 'Norwegian Breakaway');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (186, 8, 'Oasis of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (187, 2, 'Ocean Atlantic');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (188, 7, 'Ocean Countess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (189, 3, 'Ocean Dream');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (190, 5, 'Ocean Life');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (191, 5, 'Ocean Majesty');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (192, 2, 'Ocean Mist');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (193, 5, 'Ocean Star Pacific');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (194, 1, 'Oceana');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (195, 1, 'Oceanic Discoverer');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (196, 4, 'Oceanic Independence');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (197, 8, 'Oceanos');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (198, 7, 'Ocean Pearl');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (199, 7, 'Ocean Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (200, 2, 'Oriental Dragon');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (201, 5, 'Pacific');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (202, 4, 'Pacific Dawn');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (203, 8, 'Pacific Jewel');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (204, 8, 'Pacific Pearl');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (205, 5, 'Pacific Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (206, 8, 'Pacific Venus');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (207, 3, 'Pallas Athena');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (208, 1, 'Palm Beach Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (209, 8, 'Pearl Seaways');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (210, 3, 'Polaris');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (211, 5, 'Porto');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (212, 2, 'Pride of America');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (213, 6, 'Princess Daphne');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (214, 5, 'Radiance of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (215, 1, 'Rhapsody of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (216, 4, 'RIO');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (217, 2, 'Royal Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (218, 8, 'Regal Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (219, 4, 'Royal Clipper');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (220, 8, 'Royal Pacific');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (221, 8, 'Royal Iris');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (222, 3, 'Ruby Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (223, 5, 'Running on Waves');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (224, 6, 'Sagafjord');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (225, 7, 'Saga Ruby');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (226, 3, 'Saga Sapphire');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (227, 5, 'Salamis Glory');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (228, 1, 'Sapphire Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (229, 4, 'Sea Cloud');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (230, 6, 'Sea Cloud II');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (231, 7, 'Sea Diamond');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (232, 8, 'Sea Explorer');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (233, 5, 'Sea Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (234, 1, 'Seabourn Legend');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (235, 4, 'Seabourn Odyssey');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (236, 1, 'Seabourn Sojourn');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (237, 6, 'Seabourn Pride');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (238, 1, 'Seabourn Quest');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (239, 1, 'Seabourn Spirit');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (240, 4, 'SeaDream I');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (241, 6, 'SeaDream II');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (242, 1, 'Serenade of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (243, 8, 'Seven Seas Mariner');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (244, 8, 'Seven Seas Navigator');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (245, 8, 'Seven Seas Voyager');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (246, 4, 'Silver Explorer');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (247, 5, 'Silver Whisper');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (248, 8, 'Silver Spiri');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (249, 8, 'Siritara Ocean Queen');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (250, 5, 'Skorpios I');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (251, 2, 'Skorpios II');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (252, 8, 'Skorpios III');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (253, 3, 'Sovereign');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (254, 7, 'Splendour of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (255, 3, 'Star Clipper');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (256, 2, 'Star Flyer');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (257, 7, 'Star Pisces');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (258, 2, 'Star Princess');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (259, 1, 'SS Stella Solaris');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (260, 2, 'Sun 11');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (261, 3, 'Sun Vista');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (262, 2, 'SuperStar Aquarius');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (263, 6, 'SuperStar Gemini');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (264, 2, 'SuperStar Libra');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (265, 5, 'SuperStar Virgo');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (266, 5, 'Taras Shevchenko');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (267, 5, 'Thomson Majesty');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (268, 6, 'SS Uganda');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (269, 1, 'Ventura');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (270, 8, 'Viking Sea');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (271, 7, 'Viking Sky');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (272, 2, 'Viking Star');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (273, 7, 'Vision of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (274, 1, 'Voyager of the Seas');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (275, 3, 'Xpedition');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (276, 7, 'Yorktown');
INSERT INTO dreamlines_dev.ship (ship_id, sales_unit_id, name) VALUES (277, 4, 'Zenith');