// <auto-generated />
using System;
using Dreamlines.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dreamlines.Web.Migrations
{
    [DbContext(typeof(DreamlinesContext))]
    partial class DreamlinesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dreamlines.Web.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnName("booking_date");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on");

                    b.Property<int>("Price")
                        .HasColumnName("price");

                    b.Property<int>("ShipId")
                        .HasColumnName("ship_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate")
                        .IsUnique()
                        .HasName("ix_booking_date");

                    b.HasIndex("ShipId");

                    b.ToTable("booking");
                });

            modelBuilder.Entity("Dreamlines.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on");

                    b.Property<int>("CurrencyId")
                        .HasColumnName("currency_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("ix_country_name");

                    b.ToTable("country");
                });

            modelBuilder.Entity("Dreamlines.Web.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnName("symbol")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("ix_currency_name");

                    b.ToTable("currency");

                    b.HasData(
                        new { Id = 1, CreatedOn = new DateTime(2018, 9, 4, 17, 35, 53, 538, DateTimeKind.Utc), Name = "Euro", Symbol = "€" },
                        new { Id = 2, CreatedOn = new DateTime(2018, 9, 4, 17, 35, 53, 539, DateTimeKind.Utc), Name = "Brazilian real", Symbol = "R$" },
                        new { Id = 3, CreatedOn = new DateTime(2018, 9, 4, 17, 35, 53, 539, DateTimeKind.Utc), Name = "Australian dollar", Symbol = "AU$" },
                        new { Id = 4, CreatedOn = new DateTime(2018, 9, 4, 17, 35, 53, 539, DateTimeKind.Utc), Name = "Russian ruble", Symbol = "RUB" },
                        new { Id = 5, CreatedOn = new DateTime(2018, 9, 4, 17, 35, 53, 539, DateTimeKind.Utc), Name = "Renminbi", Symbol = "¥" }
                    );
                });

            modelBuilder.Entity("Dreamlines.Web.Models.SalesUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sales_unit_id");

                    b.Property<int>("CountryId")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("sales_unit");
                });

            modelBuilder.Entity("Dreamlines.Web.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ship_id");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(100);

                    b.Property<int>("SalesUnitId")
                        .HasColumnName("sales_unit_id");

                    b.HasKey("Id");

                    b.HasIndex("SalesUnitId")
                        .IsUnique()
                        .HasName("ix_sales_unit_id");

                    b.ToTable("ship");
                });

            modelBuilder.Entity("Dreamlines.Web.Models.Booking", b =>
                {
                    b.HasOne("Dreamlines.Web.Models.Ship", "Ship")
                        .WithMany("Booking")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dreamlines.Web.Models.Country", b =>
                {
                    b.HasOne("Dreamlines.Web.Models.Currency", "Currency")
                        .WithMany("Countries")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dreamlines.Web.Models.SalesUnit", b =>
                {
                    b.HasOne("Dreamlines.Web.Models.Country", "Country")
                        .WithMany("SalesUnits")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dreamlines.Web.Models.Ship", b =>
                {
                    b.HasOne("Dreamlines.Web.Models.SalesUnit", "SalesUnit")
                        .WithMany("Ships")
                        .HasForeignKey("SalesUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
